version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: be_mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: menu_db
    ports:
      - "3307:3306"
    volumes:
      - db_data_dev:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: be_dev
    env_file:
      - ./.env.docker
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/menu_db"
      PORT: 3000
    command: >
      sh -c "npx prisma migrate dev --name init || true &&
             npm run start:dev"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  db_data_dev:
