FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
RUN npx prisma generate

COPY . .

ENV NODE_ENV=development
ENV CHOKIDAR_USEPOLLING=1

CMD ["npm", "run", "start:dev"]
